#!/usr/bin/env python3

import rospy
from std_msgs.msg import UInt8
import numpy as np

def main():
    topic_command = 'uav4pe_mission_planner/command'
    pub_command = rospy.Publisher(topic_command, UInt8, queue_size=10)

    while True:
        command = np.uint8(input("Enter command number: "))
        pub_command.publish(command)
        if command == np.uint8(9):
            break

if __name__ == '__main__':
    rospy.init_node('uav4pe_navigation_commands')

    main()