#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from uav4pe_navigation import uav4pe_nav
import argparse
import rospy

def arg_parser(raw_args=None):
    # construct the argument parse and parse the arguments.
    ap = argparse.ArgumentParser()
    ap.add_argument("-sim", "--simulation", default=False,
                    help="simulation mode using QUTAS uavasr")

    if raw_args is None:
        args = vars(ap.parse_args(rospy.myargv()[1:]))
    else:
        args = vars(ap.parse_args(raw_args))

    return args

if __name__ == '__main__':
    try:
        args = arg_parser()
        uav4pe_nav.main(args)
    except Exception as e:
        print(e)
